### Create a new user
Post http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "abcde@qq.com",
  "password": "123456"
}

### find a particular user with a given id
GET http://localhost:3000/auth/1

### find all users with a given emial
GET http://localhost:3000/auth?email=129239@qq.com

### delete uese with given id
DELETE http://localhost:3000/auth/3

### update a user
PATCH http://localhost:3000/auth/10
content-type: application/json

{
  "email": "aaaaaa@bb.com",
  "password": "password"
}